---
- name: Firewalld block SSH Brute force attempts
  hosts: all
  become: true
  tasks:
    - name: firewalld rich_rule
      firewalld:
        rich_rule: rule service name="ssh" log prefix="ssh-bruteforce:" level="warning" limit value="10/m" accept limit value="10/m"
        permanent: true
        state: disabled
        immediate: true 
